config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'soup_pot#index'

  resources :items

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/recipes' => 'recipe_api#show'
  post '/recipes' => 'recipe_api#search'
  post '/recipes/:id' => 'recipe_api#create'


  resources :my_recipes, controller: 'saved_recipes', only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    collection do
      get :friends_recipes, as: :friends_recipes
    end
  end

  get '/find_friends' => 'friends#show'
  post '/find_friends' => 'friends#search'
  post '/find_friends/:id' => 'friends#send_request'
  delete '/find_friends/:id' => 'friends#destroy'
  patch '/find_friends/:id' => 'friends#accept_request'

  resources :recipes do
    resources :reviews, only: [:create, :destroy, :edit, :update]
  end

  post '/my_recipes/create' => 'saved_recipes#create'
  get '/my_recipe/:id' => 'saved_recipes#index'
  get '/my_recipe/friends_recipes/:id' => 'saved_recipes#friends_recipes'

  resources :events, only: [:new, :create, :destroy, :edit, :update, :index]
  get '/events/:ids' => 'events#index'

  post '/attendees/invite' => 'attendees#send_invite'
  patch '/events/attendees/accept' => 'attendees#accept_invite'
  delete '/attendees/delete' => 'attendees#remove_attendee'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :recipe, optional: true

  has_many :attendees, dependent: :destroy

  validates :name, presence: true
  validates :start_time, presence: true
  validates :description, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  belongs_to :recipe
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  
  validates :name, presence: true
  validates :quantity, presence: true
  validates :expiration_date, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  mount_uploader :image, SoupImageUploader

  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :cooking_time, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :profile_img, UserProfileImageUploader

  has_secure_password

  has_many :recipes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :friends, class_name: 'Friend', foreign_key: 'user_id', dependent: :destroy
  has_many :inverse_friends, class_name: 'Friend', foreign_key: 'friend_id', dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :attendees, dependent: :destroy
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }

  def self.authenticate_with_credentials(email, password)
    formattedEmail = email.strip.downcase
    user = User.find_by_email(formattedEmail)
    if user && user.authenticate(password)
      return user
    else
      return nil
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]
  def index
    @user = User.find (current_user.id)
    @items = @user.items.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @user = User.find (current_user.id)
    @item = @user.items.new(item_params)

    if @item.save
      redirect_to '/items', notice: 'CREATED'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to '/items', notice: 'EDITED'
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'DELETED!!!'
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity, :expiration_date)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/saved_recipes_controller.rb
class SavedRecipesController < ApplicationController

  def index
    @path = 'my_recipes'
    if params[:id]
      @recipe = Recipe.find params[:id]
      @ingredients = query_recipe_ingredients_to_string(@recipe)
      @review = @recipe.reviews.build
      @reviews = @recipe.reviews
      @avg_rating = @recipe.reviews.average(:rating)
    end
    @user = User.find (current_user.id)
    @recipes = @user.recipes.all
  end

  def friends_recipes
    @user = User.find (current_user.id)
    if params[:id]
      @recipe = Recipe.find params[:id]
      @ingredients = query_recipe_ingredients_to_string(@recipe)
      @review = @recipe.reviews.build
      @reviews = @recipe.reviews
      @avg_rating = @recipe.reviews.average(:rating)
    end
    @friends = @user.friends.where(pending: false).map(&:friend) + @user.inverse_friends.where(pending: false).map(&:user)
    @recipes = @friends.flat_map(&:recipes)
    render :index
  end

  def new
  end

  def create
    @user = User.find (current_user.id)
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      recipe_ingredients.each do |item|
        @ingredient = @recipe.ingredients.new(item: item)
        @ingredient.save
      end
      redirect_to my_recipes_path
    else
      raise 'Recipe failed to save!'
    end
  end

  def edit
    @recipe = Recipe.find params[:id]
    @ingredients = query_recipe_ingredients_to_string(@recipe)
  end

  def update
    @recipe = Recipe.find params[:id]

    if @recipe.update(recipe_params)
      @recipe.ingredients.destroy_all
      recipe_ingredients.each do |item|
        @ingredient = @recipe.ingredients.new(item: item)
        @ingredient.save
      end
      redirect_to '/my_recipes'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find params[:id]
    @recipe.destroy

    redirect_to '/my_recipes'
  end

  private

  def query_recipe_ingredients_to_string(recipe)
    @ingredients = recipe.ingredients.all
    @list = []
    @ingredients.each do |item|
      @list << item.item
    end
    @list = @list.join(',')
  end

  def recipe_ingredients
    params[:ingredients].split(',')
  end

  def recipe_params
    params.permit(
      :name,
      :image,
      :description,
      :cooking_time,
      :directions
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recipe_api_helper.rb
module RecipeApiHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/saved_recipes_helper.rb
module SavedRecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soup_pot_helper.rb
module SoupPotHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/saved_recipes/_recipe.html.erb
<div class="recipe-info container">
  <h2 class="recipe-name"><%= recipe.name %></h2>
  <% if recipe.web_image %>
    <img src=<%= recipe.web_image %> alt="Soup image" width="200" height="200">
  <% else %>
    <img src=<%= recipe.image %> alt="Soup image" width="200" height="200">
  <% end %>
  
  <% if @avg_rating %>
    <h2>Average Rating: <%= @avg_rating.round(1) %>/5</h2>
  <% else %>
    <h2>Average Rating: There are no ratings yet!</h2>
  <% end %>

  <h2>Ingredients:</h2>
  <ul>
    <% recipe.ingredients.each do |ingredient| %>
      <li class="ingredients-list"><%= ingredient.item %></li>
    <% end %>
  </ul>


  <h2>Cooking Instructions:</h2>
  <% if recipe.directions %>
    <h5><%= recipe.directions %></h5>
  <% else %>
    <h5>Find recipe by clicking <%= link_to "HERE!", "#{recipe.recipe_url}", target: '_blank' %></h5>
  <% end %>

  <% if current_user %>
    <h2>Reviews and Comments:</h2>
    <%= form_for [recipe, Review.new] do |form| %>
      <div class="form-group">
        <%= form.label :Write_a_review! %>
        <%= form.text_area :comment %>
      </div>

      <div class="form-group">
        <%= form.label :rating %>
        <%= form.select :rating, [5, 4, 3, 2, 1] %>
      </div>

      <%= form.submit 'Post', class: 'btn btn-primary' %>
    <% end %>
  <% end %>

  <div class="reviews">
    <% recipe.reviews.reverse_each do |review| %>
      <div class="review-details">
        <% if review.rating %>
          <h5>Posted by: <%= review.user.first_name %> <%= review.user.last_name %></h5>
          <p>Rating: <%= review.rating %>/5</p>
          <p>Comments: <%= review.comment %></p>
        <% end %>

        <% if current_user && current_user.id == review.user_id %>
          <%= link_to edit_recipe_review_path(recipe_id: recipe.id, id: review.id) do %>
            <%= fa_icon "edit", text: 'Edit', class: 'fa-icon green' %>
          <% end %>
            |
          <%= link_to recipe_review_path(recipe_id: recipe.id, id: review.id),
            method: :delete,
            data: { confirm: "Delete this review?" } do %>
              <%= fa_icon "trash", text: 'Delete', class: 'fa-icon red' %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/saved_recipes/edit.html.erb
<body class="edit-recipe">

  <header class="page-header">
    <h1>Use the form below to edit your recipe</h1>
  </header>

  <div class="form container">
    <%= form_with url: "/my_recipes/#{@recipe.id}", method: :patch do |form| %>
      <div class="form-group">
        <%= form.label "Soup name:" %>
        <%= form.text_field :name, value: "#{@recipe.name}", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Image upload:" %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Description:" %>
        <%= form.text_field :description, value: "#{@recipe.description}", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Cooking time:" %>
        <%= form.text_field :cooking_time, value: "#{@recipe.cooking_time}", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Ingredients:" %>
        <%= form.text_area :ingredients, value: "#{@ingredients}", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Cooking instructions:" %>
        <%= form.text_area :directions, value: "#{@recipe.directions}", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit "Update Recipe" %>
      </div>
    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@beccatapert?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Becca Tapert</a> on <a href="https://unsplash.com/photos/white-book-mDOGXiuVb4M?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>

app/views/saved_recipes/index.html.erb
<body class="recipes">

  <header class="page-header">
    <% if @path == 'my_recipes' %>
      <h1>
        Here are your recipes!
      </h1>
    <% else %>
      <h1>
        Here are your friends' recipes!
      </h1>
    <% end %>
  </header>

  <% if @path == 'my_recipes' %>
    <div class="upload-recipe container">
      <%= link_to 'Upload Recipe', new_my_recipe_path %>
    </div>
  <% end %>
  <div class="body-content">
    <div>
      <% @recipes.each do |recipe| %>
        <div class="saved-recipes container">
          <div>
            <% if recipe.web_image %>
              <img src=<%= recipe.web_image %> alt="Soup image" width="200" height="200">
            <% else %>
              <img src=<%= recipe.image %> alt="Soup image" width="200" height="200">
            <% end %>
          </div>
          <div class="recipe-details">
            <div class="recipe-name">
              <% if @path == 'my_recipes' %>
                <%= link_to "#{recipe.name}", "/my_recipe/#{recipe.id}" %>
              <% else %>
                <%= link_to "#{recipe.name}", "/my_recipe/friends_recipes/#{recipe.id}" %>
              <% end %>
            </div>

            <% if current_user.id != recipe.user_id %>
              <p>
                Recipe saved by <%= recipe.user.first_name %> <%= recipe.user.last_name %>
              </p>
            <% end %>

            <% if recipe.source %>
              <p>
                Source: <%= link_to "#{recipe.source}", "#{recipe.recipe_url}", target: '_blank' %>
              </p>
            <% end %>

            <% if recipe.cooking_time.to_i == 0 %>
                Cooking time: N/A
              <% else %>
                Cooking time: <%= recipe.cooking_time.to_i %> minutes
            <% end %>

            <% if recipe.description %>
              <div class="description">
                <h4>Description:</h4>
                <p><%= recipe.description %></p>
              </div>
            <% end %>

            <% if current_user.id == recipe.user_id %>
              <div class="actions fa-icon">
                <p>
                <% if !recipe.recipe_url %>
                  <%= link_to edit_my_recipe_path(recipe.id) do %><%= fa_icon "edit lg", class: "green" %><% end %> |
                <% end %>
                <%= link_to my_recipe_path(recipe.id), method: :delete, data: { confirm: 'Delete this Recipe?' } do %><%= fa_icon "trash lg", class: "red" %><% end %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <% if @recipe %>
      <%= render partial: 'saved_recipes/recipe', locals: { recipe: @recipe, current_user: current_user } %>
    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@beccatapert?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Becca Tapert</a> on <a href="https://unsplash.com/photos/white-book-mDOGXiuVb4M?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>

app/views/saved_recipes/new.html.erb
<body class="upload-item">

  <header class="page-header">
    <h1>Tell us about your soup recipe!</h1>
  </header>

  <div class="form container">
    <%= form_with url: "/my_recipes/create", method: :post do |form| %>
      <div class="form-group">
        <%= form.label "Give your soup a name:" %>
        <%= form.text_field :name, placeholder: "ex: Mary's Carrot Soup", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Upload an image:" %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Write a short description:" %>
        <%= form.text_field :description, placeholder: "ex: A light soup for a sunny day", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "How long does it take to cook?" %>
        <%= form.text_field :cooking_time, placeholder: "ex: 20 minutes", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "List all ingredients and their amounts here. Seperate with commas!" %>
        <%= form.text_area :ingredients, placeholder: "ex: 2 carrots, a pinch of salt, ...", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "How do you make it?" %>
        <%= form.text_area :directions, placeholder: "ex: Step one: wash and peel your carrots...", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit "Upload Recipe"%>
      </div>
    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@beccatapert?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Becca Tapert</a> on <a href="https://unsplash.com/photos/white-book-mDOGXiuVb4M?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>