config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'soup_pot#index'

  resources :items

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/recipes' => 'recipe_api#show'
  post '/recipes' => 'recipe_api#search'
  post '/recipes/:id' => 'recipe_api#create'


  resources :my_recipes, controller: 'saved_recipes', only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    collection do
      get :friends_recipes, as: :friends_recipes
    end
  end

  get '/find_friends' => 'friends#show'
  post '/find_friends' => 'friends#search'
  post '/find_friends/:id' => 'friends#send_request'
  delete '/find_friends/:id' => 'friends#destroy'
  patch '/find_friends/:id' => 'friends#accept_request'

  resources :recipes do
    resources :reviews, only: [:create, :destroy, :edit, :update]
  end

  post '/my_recipes/create' => 'saved_recipes#create'
  get '/my_recipe/:id' => 'saved_recipes#index'
  get '/my_recipe/friends_recipes/:id' => 'saved_recipes#friends_recipes'

  resources :events, only: [:new, :create, :destroy, :edit, :update, :index]
  get '/events/:ids' => 'events#index'

  post '/attendees/invite' => 'attendees#send_invite'
  patch '/events/attendees/accept' => 'attendees#accept_invite'
  delete '/attendees/delete' => 'attendees#remove_attendee'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :recipe, optional: true

  has_many :attendees, dependent: :destroy

  validates :name, presence: true
  validates :start_time, presence: true
  validates :description, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  belongs_to :recipe
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  
  validates :name, presence: true
  validates :quantity, presence: true
  validates :expiration_date, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  mount_uploader :image, SoupImageUploader

  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :cooking_time, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :profile_img, UserProfileImageUploader

  has_secure_password

  has_many :recipes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :friends, class_name: 'Friend', foreign_key: 'user_id', dependent: :destroy
  has_many :inverse_friends, class_name: 'Friend', foreign_key: 'friend_id', dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :attendees, dependent: :destroy
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }

  def self.authenticate_with_credentials(email, password)
    formattedEmail = email.strip.downcase
    user = User.find_by_email(formattedEmail)
    if user && user.authenticate(password)
      return user
    else
      return nil
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :store_previous_url, only: [:new, :edit, :destroy]

  def store_previous_url
    session[:previous_url] = request.referer if request.referer
  end

  def index
    if current_user
      if params[:ids]
        @events = Event.where(id: event_ids)
      end
      @invite_options = friends_ids.map { |id| ["#{User.find(id).first_name} #{User.find(id).last_name}", "#{id}"]}
      start_date = params.fetch(:start_date, Date.today).to_date
      @my_events = Event.where(user_id: current_user.id, start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
      @friends_events = Event.where(user_id: friends_ids, private: false, start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
      @private_events = Event.joins(:attendees).where(attendees: { user_id: current_user.id }, private: true).where.not(user_id: current_user.id)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.events.new(event_params)

    if @event.save
      redirect_to session.delete(:previous_url), allow_other_host: true || root_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to session.delete(:previous_url), allow_other_host: true || root_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to '/events'
  end

  private

  def friends_ids
    user = User.find(current_user.id)
    user.friends.where(pending: false).pluck(:friend_id) + user.inverse_friends.where(pending: false).pluck(:user_id)
  end

  def event_ids
    JSON.parse(params[:ids])
  end

  def event_params
    params.require(:event).permit(:name, :start_time, :description, :private)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]
  def index
    @user = User.find (current_user.id)
    @items = @user.items.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @user = User.find (current_user.id)
    @item = @user.items.new(item_params)

    if @item.save
      redirect_to '/items', notice: 'CREATED'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to '/items', notice: 'EDITED'
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'DELETED!!!'
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity, :expiration_date)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/', notice: 'User created!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :profile_img,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recipe_api_helper.rb
module RecipeApiHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/saved_recipes_helper.rb
module SavedRecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soup_pot_helper.rb
module SoupPotHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event-info">
  <% events.each do |event| %>
    <div class="container">
      <h2 class="event-name">
        <% if event.attendees.exists?(user_id: current_user.id, attending: true) %>
          <%= fa_icon "check", class: "green" %>
        <% elsif event.user_id == current_user.id && event.private == true %>
          <%= fa_icon "star", class: "light-green" %>
        <% elsif event.private == true %>
          <%= fa_icon "star", class: "pink" %>
        <% elsif current_user.id == event.user_id %>
          <%= fa_icon "circle", class: "light-green" %>
        <% else %>
          <%= fa_icon "circle", class: "pink" %>
        <% end %>
        <%= event.name %>
      </h2>
      <h4>
        <% if event.private == true %>
          This is a private event!
        <% else %>
          This is an open event!
        <% end %>
        <% if !event.attendees.exists?(user_id: current_user.id, attending: true) %>
          <%= link_to "attendees/accept?user_id=#{current_user.id}&event_id=#{event.id}", method: :patch, class: "attend-event" do %>
            <%= fa_icon "check", text: "Attend Event" %>
          <% end %>
        <% end %>
      </h4>

      <% if current_user.id != event.user_id %>
        <h4 class="event-owner">
          Event host: <%= event.user.first_name %> <%= event.user.last_name %>
        </h4>
      <% end %>

      <p class="event-description">
        <%= event.description %>
      <p>

      <p class="event-time">
        Event scheduled for: <%= event.start_time %>
      </p>

      <h4>Invited:</h4>
      <ul class="invited-list">
        <% event.attendees.each do |invite| %>
          <% if invite.attending == false %>
            <li class="invited-friend">
              <%= invite.user.first_name %> <%= invite.user.last_name %>
              <% if current_user.id == event.user_id %>
                <%= link_to "/attendees/delete?user_id=#{invite.user.id}&event_id=#{event.id}", method: :delete, data: { confirm: 'Do you want to cancel this invitation?' } do %>
                  <%= fa_icon "trash lg", class: "red" %>
                <% end %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>

      <h4>Attending:</h4>
      <ul class="attending-list">
        <% event.attendees.each do |invite| %>
          <% if invite.attending == true %>
            <li class="attending-friend">
              <%= invite.user.first_name %> <%= invite.user.last_name %>
              <% if current_user.id == invite.user.id %>
                <%= link_to "/attendees/delete?user_id=#{invite.user.id}&event_id=#{event.id}", method: :delete, data: { confirm: 'Do you no longer wish to attend this event?' } do %>
                  <%= fa_icon "trash lg", class: "red" %>
                <% end %>
              <% elsif current_user.events.exists?(id: event.id) %>
                <%= link_to "/attendees/delete?user_id=#{invite.user.id}&event_id=#{event.id}", method: :delete, data: { confirm: 'Remove this attendee?' } do %>
                  <%= fa_icon "trash lg", class: "red" %>
                <% end %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>

      <% if current_user.id == event.user_id %>
        <div class="invite-form">
          <%= form_with url: "/attendees/invite", method: :post do |form| %>
            <%= form.select :friend_id, invite_options %>
            <%= hidden_field :event_id, event.id %>
            <%= form.submit 'Send Invitation' %>
          <% end %>
        </div>
      <% end %>

      <% if current_user.id == event.user_id %>
        <div class="actions">
          <%= link_to edit_event_path(event.id) do %>
            <%= fa_icon "edit lg", class: "green" %> |
          <% end %>
          <%= link_to event_path(event.id), method: :delete, data: { confirm: 'Delete this event?' } do %>
            <%= fa_icon "trash lg", class: "red" %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<body class="edit-event">

<header class="page-header">
    <h1>Edit Event!</h1>
</header>

<div class='container'>
  <%= form_with(model: @event, url: event_path(@event), method: :patch) do |form| %>
    <div class="form-group">
      <%= form.label "Private Event?" %>
      <%= form.check_box :private %>
    </div>

    <div class="form-group">
      <%= form.label "Title" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label "Description" %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label "Start Time" %>
      <%= form.date_field :start_time, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit "Create Event", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<%= link_to "Go Back", events_path, class: "btn btn-primary"%>

<div class="attribution">
    Photo by <a href="https://unsplash.com/@3dottawa?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Point3D Commercial Imaging Ltd.</a> on <a href="https://unsplash.com/photos/a-kitchen-with-white-cabinets-and-stainless-steel-appliances-0dj9V9s-R9c?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
</div>

</body>

app/views/events/index.html.erb
<body class="events-page">

  <header class="page-header">
    <h1>
      Here's your event calendar!
    </h1>
    <h2>
      You can plan and attend events with your friends here.
    </h2>
  </header>

  <div class="body-content">
    <div class="calendar container">
      <%= month_calendar(events: @my_events + @friends_events + @private_events) do |date, events| %>
        <div class="events-link" onclick='window.location.href="/events/<%= events.pluck(:id) %>"'>
          <%= date.day %>
          <% events.each do |event| %>
            <% if event.attendees.exists?(user_id: current_user.id, attending: true) %>
              <%= fa_icon "check lg", class: "green" %>
            <% elsif event.user_id == current_user.id && event.private == true %>
              <%= fa_icon "star lg", class: "light-green" %>
            <% elsif event.private == true %>
              <%= fa_icon "star lg", class: "pink" %>
            <% elsif current_user.id == event.user_id %>
              <%= fa_icon "circle lg", class: "light-green" %>
            <% else %>
              <%= fa_icon "circle lg", class: "pink" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <p class="legends">
      <%= fa_icon "circle lg", class: "light-green" %> your event |
      <%= fa_icon "star lg", class: "light-green" %> your private event |
      <%= fa_icon "check lg", class: "green" %> attending event
      </p>
      <p class="legends">
      <%= fa_icon "circle lg", class: "pink" %> friend's event |
      <%= fa_icon "star lg", class: "pink" %> friend's private event |
      <%= fa_icon "square lg", class: "yellow" %> current day
      </p>
      <div class="form-group create-event-button">
        <%= link_to 'Create Event', new_event_path, class: "btn btn-primary" %>
      </div>
    </div>

    <% if @events %>
      <%= render partial: 'event', locals: { events: @events, invite_options: @invite_options, invites: @invites } %>
    <% end %>
  </div>
  <div class="attribution">
    Photo by <a href="https://unsplash.com/@3dottawa?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Point3D Commercial Imaging Ltd.</a> on <a href="https://unsplash.com/photos/a-kitchen-with-white-cabinets-and-stainless-steel-appliances-0dj9V9s-R9c?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>

app/views/events/new.html.erb
<body class="events-page">

  <header class="page-header">
      <h1>Tell us about your event!</h1>
  </header>

  <div class='new-event container'>
    <%= form_with(model: @event, url: events_path) do |form| %>
      <div class="checkbox-container form-group">
        <%= form.label "Private Event?" %>
        <%= form.check_box :private, class: 'checkbox' %>
      </div>

      <div class="form-group">
        <%= form.label "Title" %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Description" %>
        <%= form.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label "Start Time" %>
        <%= form.date_field :start_time, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit "Create Event", class: "btn btn-primary" %>
      </div>
    <% end %>

    <div class="attribution">
      Photo by <a href="https://unsplash.com/@3dottawa?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Point3D Commercial Imaging Ltd.</a> on <a href="https://unsplash.com/photos/a-kitchen-with-white-cabinets-and-stainless-steel-appliances-0dj9V9s-R9c?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    </div>
  </div>

    <%= link_to "Go Back", events_path, class: "btn btn-primary"  %>

</body>

app/views/items/edit.html.erb
<body class="edit-item">

  <header class="page-header">
    <h1>Alter the fields below to edit your fridge item</h1>
  </header>

  <div class="form container">
    <%= form_for @item do |form| %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.text_field :quantity, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :expiration_date %>
        <%= form.date_field :expiration_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit %>
      </div>

    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@elloproducts?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ello</a> on <a href="https://unsplash.com/photos/green-and-pink-plastic-container-AEU9UZstCfs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>

app/views/items/index.html.erb
<body class="inventory">

  <header class="page-header">
    <h1>Your Fridge Contents:</h1>
  </header>

  <div class="table-container">
    <%= form_for :item do |form| %>
      <table class="table">
        <thead>
          <tr class="table-row">
            <td class="table-data">Name</td>
            <td class="table-data">Quantity</td>
            <td class="table-data">Expiry</td>
            <td class="table-data">Action</td>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
          <tr class="table-row">
            <td class="table-data"><%= item.name %></td>
            <td class="table-data"><%= item.quantity %></td>
            <td class="table-data"><%= item.expiration_date %></td>
            <td class="table-data"><%= link_to 'Edit', edit_item_path(item.id) %> | <%= link_to item_path(item.id), method: :delete, data: { confirm: 'Remove this item?' } do %><%= fa_icon "trash"%><% end %></td>
          </tr>
          <% end %>
          <tr class="table-row">
            <td class="table-data"><%= form.text_field :name %></td>
            <td class="table-data"><%= form.text_field :quantity %></td>
            <td class="table-data"><%= form.date_field :expiration_date %></td>
            <td class="table-data"><%= form.submit %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@elloproducts?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ello</a> on <a href="https://unsplash.com/photos/green-and-pink-plastic-container-AEU9UZstCfs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>

app/views/items/show.html.erb
<%= @item.name %>
<div><%= @item.quantity %> </div>
<div><%= @item.expiration_date %></div>


<%= link_to 'back', items_path %>

app/views/users/new.html.erb
<body class="signup">

  <header class="page-header">
    <h1>Welcome to Soup Pot! We're always excited to get new members!</h1>
  </header>

  <div class="form container">
    <%= form_for :user, url: '/users' do |form| %>

      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :profile_image %>
        <%= form.file_field :profile_img, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <div class="attribution">
    Photo by <a href="https://unsplash.com/@edgarraw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Odiseo Castrejon</a> on <a href="https://unsplash.com/photos/brown-wooden-shelf-CX8ooha2yLA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  </div>

</body>